### PR TITLE
typings

### PR DESCRIPTION
**Pull request by gossi**
Typings for `Component` and `@tracked`. I took the comments from https://github.com/glimmerjs/glimmer.js/tree/master/packages/@glimmer/component/src

### CODE REVIEW

**Comment by gossi** [comment]
@rwjblue can this be merged as well for the next release?

**Comment by rwjblue** [comment]
I dunno. I’m not really a big fan of shipping typings like this. I’d much prefer to migrate to TS across the board (and therefore ensure that the types stay in sync) than this. 

I did take an initial crack at it but gave up after running out of time, are you interested in giving it a go?

**Comment by gossi** [comment]
I get your point. I see the typings as an easy fix for just js files, that when present at the original project, I don't have to put into my consuming project over and over again. Isn't the goal of this project to be a playground until they are turned into _real_ glimmer components? If so, the days of this repo are counted - are they?

**Comment by rwjblue** [comment]
Unsure, we’ve been hearing about “glimmer components” in one form or another since 1.13, still nothin’ shipped. 😈

**Comment by gossi** [comment]
Hmm ok, apart from wether this will be turned into glimmer components or TS itself, typings would help until either of that is done.

**Comment by mike-north** [comment]
If @rwjblue is not ready to accept types into this package, you can always create ambient types in another repo

Here's a guide to the process: https://mike.works/blog/post/guide-to-typescript-ambient-declarations-13d3c45

**Pull request closed without merging**
